camel:
  springboot:
    # The Camel context name
    name: camelContext
  # To enable global SSL
  component:
    netty:
      use-global-ssl-context-parameters: true
  ssl:
    config:
      key-managers:
        key-password: "redhat456"
        key-store:
          resource: "/keystore.kjs"
          password: "redhat456"
          type: "jks"
      trust-managers:
        key-store:
          resource: "/keystore.kjs"
          password: "redhat456"
          type: "jks"

# Binding health checks to a different port
#management:
#  port: 8081

#server:
#  port: 8443
  
# disable all management enpoints except health
#endpoints:
#  enabled: false
#  health:
#    enabled: true

